name: The Lost Kingdom of Omera
theme: minima
lsi: false
safe: true
source: Omera
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


