name: The Lost Kingdom of Omera
logo: /assets/img/logo.png
description: A D&D campaign setting aimed at younger players.
baseurl: /Omera
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
markdown: GFM
lsi: false
safe: true
source: Omera
incremental: false
highlighter: rouge
permalink: pretty
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
